In [0]:
import numpy as np

PCA(Principle Component Analysis)

In [0]:
x1 = np.arange(0, 10, .2)
x2 = x1 + np.random.randn(len(x1))

In [0]:
X = np.c_[(x1, x2)]
good = (x1 > 5) | (x2 > 5) # some arbitrary classes
bad = ~good # to make the example look good

In [34]:
good, bad

(array([False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False,  True,  True, False, False, False, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True]),
 array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True, False, False,  True,  True,  True,  True, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False]))

In [35]:
from sklearn import linear_model, decomposition, datasets
pca = decomposition.PCA(n_components=1)
Xtrans = pca.fit_transform(X)

pca.explained_variance_ratio_

array([0.97556621])

LDA(Linear Discriminant Analysis)

In [37]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

lda_inst = LDA(n_components=1)
Xtrans = lda_inst.fit_transform(X, good)
print(Xtrans)

[[-3.43395538]
 [-2.78918152]
 [-2.30256773]
 [-3.18698684]
 [-3.18158006]
 [-2.33691767]
 [-2.54609535]
 [-2.74069786]
 [-2.8745754 ]
 [-2.20090497]
 [-2.08969822]
 [-1.92103907]
 [-1.40114652]
 [-1.62497585]
 [-1.01474658]
 [-1.10339123]
 [-1.23496989]
 [-0.5186014 ]
 [-0.95490823]
 [-1.15603228]
 [ 0.41162298]
 [ 0.11438734]
 [-0.46490143]
 [-0.66107607]
 [-0.15420318]
 [-0.3788661 ]
 [ 0.5251554 ]
 [ 0.03659079]
 [ 0.86952252]
 [ 1.30687653]
 [ 0.45860698]
 [ 0.74298386]
 [ 1.43324675]
 [ 1.26200915]
 [ 1.02255271]
 [ 1.70711992]
 [ 1.50880873]
 [ 1.30620538]
 [ 2.8182207 ]
 [ 1.6008472 ]
 [ 1.47072468]
 [ 1.3178757 ]
 [ 2.9528879 ]
 [ 2.70752964]
 [ 3.12394593]
 [ 1.95321035]
 [ 2.74121761]
 [ 2.41896958]
 [ 2.95213526]
 [ 3.50876525]]


In [0]:
# PCA는 비지도, LDA는 지도학습
# 샘플이 적을때는 PCA가 잘 동작
# 샘플이 충분하면 LDA가 잘 동작

MDS(Multidimensional Scaling)

In [38]:
X = np.c_[np.ones(5), np.full(5, 2), np.full(5, 10)].T
print(X)

[[ 1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.]
 [10. 10. 10. 10. 10.]]


In [39]:
from sklearn import manifold

mds = manifold.MDS(n_components=3)
Xtrans = mds.fit_transform(X)
Xtrans

array([[-2.33074147, -6.71906983,  1.77064923],
       [-2.64224107, -4.68626191,  0.57635602],
       [ 4.97298254, 11.40533173, -2.34700525]])