Numpy

In [0]:
import numpy as np

In [0]:
# 배열 만들기
a = np.array([1, 2, 3]) # rank 1
b = np.array([[1, 2, 3], [4, 5, 6]]) # rank 2

In [4]:
# shape 확인
a, a.shape

(array([1, 2, 3]), (3,))

In [5]:
b, b.shape

(array([[1, 2, 3],
        [4, 5, 6]]), (2, 3))

In [6]:
# 인덱싱
a[0], b[0, 2]

(1, 3)

In [7]:
a[:2], b[:1, :]

(array([1, 2]), array([[1, 2, 3]]))

In [10]:
a = np.array([[1, 2], [3, 4], [5, 6]])

bool_idx = (a > 2)
bool_idx, type(bool_idx)

(array([[False, False],
        [ True,  True],
        [ True,  True]]), numpy.ndarray)

In [11]:
# 자료형
x = np.array([1, 2])
x.dtype

dtype('int64')

In [12]:
y = np.array([1.0, 2.0])
y.dtype

dtype('float64')

In [14]:
x = np.array([1, 2], dtype=np.float64)
x.dtype, x

(dtype('float64'), array([1., 2.]))

In [17]:
# 숫자 배열 생성
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [18]:
b = np.ones((2, 2))
b

array([[1., 1.],
       [1., 1.]])

In [21]:
c = np.full((2, 2), 7)
c, c.dtype

(array([[7, 7],
        [7, 7]]), dtype('int64'))

In [24]:
d = np.eye(4)
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
e = np.random.random((2, 2))
e

array([[0.75682157, 0.50066666],
       [0.69369359, 0.08837711]])

In [29]:
# 배열 연산
x = np.array([[1, 2], [3, 4]], dtype = np.float64)
y = np.array([[5, 6], [7, 8]], dtype = np.float64)
x

array([[1., 2.],
       [3., 4.]])

In [28]:
y

array([[5., 6.],
       [7., 8.]])

In [30]:
np.add(x, y)

array([[ 6.,  8.],
       [10., 12.]])

In [31]:
np.subtract(x, y)

array([[-4., -4.],
       [-4., -4.]])

In [32]:
np.divide(x, y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [33]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [0]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

In [35]:
v.dot(w), np.dot(v, w)

(219, 219)

In [36]:
x.dot(v), np.dot(x, v)

(array([29, 67]), array([29, 67]))

In [39]:
x.dot(y), np.dot(x, y)

(array([[19, 22],
        [43, 50]]), array([[19, 22],
        [43, 50]]))

In [41]:
x = np.array([[1, 2], [3, 4]])

print(np.sum(x))
print(np.sum(x, axis = 0)) # 각 col들을 더한 값
print(np.sum(x, axis = 1)) # 각 row들을 더한 값

10
[4 6]
[3 7]


In [0]:
# broadcasting
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
# y = x + v
# y

In [43]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [44]:
v

array([1, 0, 1])

In [45]:
x + v

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])