In [0]:
import numpy as np
import matplotlib.pyplot as plt

reshape()

In [4]:
%%time
x = 0
for i in range(100000000):
  x+=1
x

CPU times: user 9.56 s, sys: 1.46 ms, total: 9.56 s
Wall time: 9.58 s


In [2]:
%%time
arr = np.arange(12)
print(arr)

arr2 = np.reshape(arr, (4, 3)) # arr.reshape(4,3)도 가능
print(arr2)

print()
arr[1] = 100
print(arr)
print(arr2)

print(arr2.base is arr)
print(arr.base is arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[  0 100   2   3   4   5   6   7   8   9  10  11]
[[  0 100   2]
 [  3   4   5]
 [  6   7   8]
 [  9  10  11]]
True
False
CPU times: user 1.65 ms, sys: 0 ns, total: 1.65 ms
Wall time: 5.47 ms


In [0]:
# call by reference가 아니라 value이고 싶다면? 복사본 이용하자!
arr3 = arr.reshape(4,3).copy()
print(arr3)

print(arr3.base is arr)

[[  0 100   2]
 [  3   4   5]
 [  6   7   8]
 [  9  10  11]]
False


In [0]:
# 데이터가 너무 많아서 몇행 몇열로 설정해야 할지 모르겠다면? -1을 이용 그리고 형태가 맞아야함!!
arr2 = arr.reshape(3,-1)
print(arr2)

[[  0 100   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


In [0]:
# 다차원 배열을 1차원으로 만들기 --> ravel()
arr4 = np.ravel(arr3)
print(arr4)

[  0 100   2   3   4   5   6   7   8   9  10  11]


resize()

In [0]:
# reshape와 다르게 형태가 달라도 error가 발생하지 않고 수가 부족하면 배열의 처음부터 다시한다
arr = np.arange(10)

# 야 이거 좀 다른데 공부좀 해야할듯
arr2 = np.resize(arr, (2, 7))
print(arr)
arr.resize(2,7)
print(arr)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4 5 6]
 [7 8 9 0 0 0 0]]
[[0 1 2 3 4 5 6]
 [7 8 9 0 1 2 3]]


array 결합하기

In [0]:
# 가로방형으로 결합하기: np.hstack() 열 개수는 노상관
np.random.seed(1111)
arr1 = np.random.randint(0, 10, (2,3))
print(arr1)
arr2 = np.random.randint(0, 10, (2, 5))
print(arr2)
result = np.hstack((arr1, arr2))
result

[[7 5 1]
 [2 4 8]]
[[6 4 8 6 2]
 [6 8 9 3 4]]


array([[7, 5, 1, 6, 4, 8, 6, 2],
       [2, 4, 8, 6, 8, 9, 3, 4]])

In [0]:
# 세로로 결합하기: np.vstack(tuple) 행 개수는 노상관
arr1 = np.random.randint(0, 10, (2,3))
print(arr1)
arr2 = np.random.randint(0, 10, (3, 3))
print(arr2)
result = np.vstack((arr1, arr2))
result
# 둘다 지원하는건 np.concatenate()이다. 기본값은 axis=0 세로길이 늘어나는거고 axis=1해주면 가로가 늘어남

[[8 9 9]
 [7 2 0]]
[[4 8 5]
 [5 1 2]
 [0 7 5]]


array([[8, 9, 9],
       [7, 2, 0],
       [4, 8, 5],
       [5, 1, 2],
       [0, 7, 5]])

Indexing & slicing!!

In [0]:
arr = np.arange(20)
arr[2], arr[1:3], arr[:]

(2,
 array([1, 2]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]))

In [0]:
arr[1::2], arr[3::5], arr[-1:]

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]),
 array([ 3,  8, 13, 18]),
 array([19]))

In [0]:
arr = np.arange(0,12).reshape(3,4)
print(arr)

arr[1,2], arr[:,0], arr[1:3, 1:3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


(6, array([0, 4, 8]), array([[ 5,  6],
        [ 9, 10]]))

In [0]:
arr[:], arr[:,:] # 같은거

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]))

In [0]:
mask = arr%2 == 0
print(mask)
print(arr[mask])

[[ True False  True False]
 [ True False  True False]
 [ True False  True False]]
[ 0  2  4  6  8 10]


Fancy indexing

In [0]:
arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [0]:
print(arr[2,2]) # indexing
print(arr[1:2, 2]) # slicing
print(arr[[0,2], 2]) # 0, 2행의 2열을 도출
print(arr[2, [0,2]])
print(arr[[0,2],1:])

10
[6]
[ 2 10]
[ 8 10]
[[ 1  2  3]
 [ 9 10 11]]


배열 연산

In [0]:
np.random.seed(1)
arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.random.randint(1, 10, (2,3))
print(arr1+arr2)

[[ 7 11  9]
 [ 5  6  8]]


In [0]:
print(arr1 + 10) # broadcasting

[[11 12 13]
 [14 15 16]]


In [0]:
# 그밖에 np.add, np.subtract, np.divide, np.sqrt, np.dot이 있다
arr3 = arr1.reshape(3,2).copy()
np.dot(arr1, arr3) # 2x3 . 3x2

array([[22, 28],
       [49, 64]])

In [0]:
print(arr1)

np.sum(arr1), arr1.sum()

[[1 2 3]
 [4 5 6]]


(21, 21)

In [0]:
np.cumsum(arr1)

array([ 1,  3,  6, 10, 15, 21])

In [0]:
# 여러 통계값들
np.mean(arr1), np.max(arr1), np.min(arr1), np.std(arr1)

(3.5, 6, 1, 1.707825127659933)

In [0]:
np.sqrt(arr1), np.log10(arr1)

(array([[1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]]),
 array([[0.        , 0.30103   , 0.47712125],
        [0.60205999, 0.69897   , 0.77815125]]))

In [0]:
print(arr1)
arr1.sum(), arr1.sum(axis=0), np.sum(arr1, axis=1) # 0이 행방향, 1이 열방향이라는데 감이 잘 안온다

[[1 2 3]
 [4 5 6]]


(21, array([5, 7, 9]), array([ 6, 15]))

delete

In [0]:
# np.delete(): axis를 기준으로 행과 열을 삭제
# 지정하지 않으면 1차배열로 변환된 후 해당요소 삭제
# 원본은 유지, 삭제된 복사본을 return한다
arr = np.arange(12).reshape(3,4)
print(arr,'\n')

print(np.delete(arr,1),'\n')

print(np.delete(arr,1, axis=0),'\n')

print(np.delete(arr,1, axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[ 0  2  3  4  5  6  7  8  9 10 11] 

[[ 0  1  2  3]
 [ 8  9 10 11]] 

[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


In [0]:
# sort도 넣을까?